name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration
